# Generated by Django 3.2.9 on 2022-05-04 07:28

from django.db import migrations, models
import user_avatar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('model_file_path', models.FileField(upload_to=user_avatar.models.user_directory_path)),
            ],
            options={
                'db_table': 'UserAvatar',
            },
        ),
    ]
