# Generated by Django 3.2.9 on 2022-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=256)),
                ('content_name', models.CharField(max_length=256)),
                ('content_type', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_path', models.CharField(default='', max_length=256)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=256)),
                ('access_type', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=300)),
                ('file_name', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=256)),
                ('build_target', models.CharField(max_length=200)),
                ('uploaded_by', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
    ]
