# Generated by Django 3.2.9 on 2022-05-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contents',
            table='Contents',
        ),
    ]
