# Generated by Django 3.2.9 on 2022-04-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('ceo_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=30)),
                ('technology', models.CharField(default='IT', max_length=1000)),
                ('language', models.CharField(default='EN', max_length=100)),
                ('company_created_by', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Companyinfo',
            },
        ),
    ]
