# Generated by Django 3.2.9 on 2022-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('media_id', models.CharField(max_length=128)),
                ('media_type', models.CharField(max_length=128)),
                ('media_path', models.CharField(max_length=1028)),
            ],
            options={
                'db_table': 'Session_Media',
            },
        ),
    ]
