# Generated by Django 3.2.9 on 2022-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.CharField(max_length=1000)),
                ('session_id', models.CharField(max_length=100)),
                ('invite_link', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'InviteList',
            },
        ),
    ]
