# Generated by Django 3.2.9 on 2022-04-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteelist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inviteelist',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
