# Generated by Django 3.2.9 on 2022-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occulus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oculus',
            name='oculus_id',
            field=models.CharField(max_length=100),
        ),
    ]
