# Generated by Django 3.2.9 on 2022-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('invite_email', models.CharField(max_length=1000)),
                ('content_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ContentAccess',
            },
        ),
    ]
