# Generated by Django 3.2.9 on 2022-01-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session_users',
            table='session_users',
        ),
    ]
