# Generated by Django 3.2.9 on 2022-05-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_user', '0003_auto_20220106_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session_users',
            table='Session_Users',
        ),
    ]
