# Generated by Django 3.2.9 on 2021-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0004_auto_20211214_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
