# Generated by Django 3.2.9 on 2021-12-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20211216_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='invited_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
