# Generated by Django 3.2.9 on 2021-12-17 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_sessionmodel_invited_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='date_modified',
            field=models.CharField(default=datetime.date(2021, 12, 17), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='end_date',
            field=models.CharField(default=datetime.date(2021, 12, 17), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='invited_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_date',
            field=models.CharField(default=datetime.date(2021, 12, 17), max_length=50),
        ),
    ]
