# Generated by Django 3.2.9 on 2021-12-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211217_0505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionModel',
            new_name='SessionsModel',
        ),
    ]
