# Generated by Django 3.2.9 on 2021-12-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_sessionmodel_sessionsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionsModel',
            new_name='SessionModel',
        ),
    ]
