# Generated by Django 3.2.9 on 2021-12-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_sessionmodel_invited_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='invited_list',
            field=models.TextField(null=True),
        ),
    ]
