# Generated by Django 3.2.9 on 2021-12-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20211217_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='invited_emails',
        ),
    ]
