# Generated by Django 3.2.9 on 2021-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20211217_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='invited_emails',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
