# Generated by Django 3.2.9 on 2021-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_sessionmodel_invited_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='invited_emails',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
