# Generated by Django 3.2.9 on 2021-12-21 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0017_alter_sessionmodel_invited_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionmodel',
            old_name='created_by',
            new_name='host_user_email',
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='date_modified',
            field=models.CharField(default=datetime.date(2021, 12, 21), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='end_date',
            field=models.CharField(default=datetime.date(2021, 12, 21), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_date',
            field=models.CharField(default=datetime.date(2021, 12, 21), max_length=50),
        ),
    ]
