# Generated by Django 3.2.9 on 2021-12-22 09:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0018_auto_20211221_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Session_Media',
        ),
        migrations.DeleteModel(
            name='Session_Users',
        ),
        migrations.DeleteModel(
            name='SessionModel',
        ),
    ]
