# Generated by Django 3.2.9 on 2021-12-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0019_auto_20211222_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='auth_provider',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='provider',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='role',
            field=models.CharField(default='user', max_length=30, null=True),
        ),
    ]
