# Generated by Django 3.2.9 on 2021-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0020_auto_20211228_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
