# Generated by Django 3.2.9 on 2021-12-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_registermodel_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='auth_provider',
        ),
    ]
