# Generated by Django 3.2.9 on 2022-01-04 10:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('login', '0022_remove_registermodel_auth_provider'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registermodel',
            table='users',
        ),
    ]
