# Generated by Django 3.2.9 on 2022-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0026_alter_registermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='phone_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='company_name',
            field=models.CharField(default='xrconnect-client', max_length=128, null=True),
        ),
    ]
