# Generated by Django 3.2.9 on 2022-04-25 07:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0027_auto_20220425_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
