# Generated by Django 3.2.9 on 2022-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('login', '0028_rename_phone_num_registermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='vrcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
