# Generated by Django 3.2.9 on 2021-12-22 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('media_id', models.CharField(max_length=128, unique=True)),
                ('media_type', models.CharField(max_length=128)),
                ('thumbnail_path', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=128)),
                ('upload_by', models.CharField(max_length=128)),
                ('access_type', models.CharField(max_length=128)),
                ('permitted_users', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('media_id', models.CharField(max_length=128)),
                ('media_type', models.CharField(max_length=128)),
                ('media_path', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('user_role', models.CharField(max_length=128)),
                ('user_avatar', models.CharField(max_length=1028)),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.CharField(max_length=50)),
                ('date_modified', models.CharField(default=datetime.date(2021, 12, 22), max_length=50)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('parent_event_name', models.CharField(max_length=128)),
                ('session_status', models.BooleanField(default=True)),
                ('access_type', models.CharField(max_length=128)),
                ('max_users', models.CharField(max_length=10)),
                ('invited_emails', models.CharField(blank=True, max_length=1000, null=True)),
                ('host_user_email', models.EmailField(max_length=254, null=True)),
                ('start_date', models.CharField(default=datetime.date(2021, 12, 22), max_length=50)),
                ('end_date', models.CharField(default=datetime.date(2021, 12, 22), max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('environment_id', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
