# Generated by Django 3.2.9 on 2022-01-06 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=None)),
                ('date_modified', models.DateTimeField(default=None)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('parent_event_name', models.CharField(max_length=128)),
                ('session_status', models.CharField(max_length=128)),
                ('access_type', models.CharField(max_length=128)),
                ('max_users', models.CharField(max_length=10)),
                ('host_user_email', models.EmailField(max_length=254, null=True)),
                ('start_date', models.CharField(default=datetime.date(2022, 1, 6), max_length=50)),
                ('end_date', models.CharField(default=datetime.date(2022, 1, 6), max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('environment_id', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Session_Media',
        ),
        migrations.DeleteModel(
            name='Session_Users',
        ),
        migrations.DeleteModel(
            name='SessionModel',
        ),
    ]
