# Generated by Django 4.0.1 on 2022-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0002_alter_usercontentmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontentmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
