# Generated by Django 3.2.9 on 2022-01-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0004_auto_20220106_0613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercontentmodel',
            table='user_contents',
        ),
    ]
