# Generated by Django 3.2.9 on 2022-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0005_alter_usercontentmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentmodel',
            name='content_load_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
