# Generated by Django 3.2.9 on 2022-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0006_usercontentmodel_content_load_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentmodel',
            name='path',
            field=models.CharField(default=' ', max_length=256, null=True),
        ),
    ]
