# Generated by Django 3.2.9 on 2022-05-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0007_usercontentmodel_path'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercontentmodel',
            table='User_Contents',
        ),
    ]
