# Generated by Django 3.2.9 on 2022-01-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='path',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='permitted_users',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='thumbnail_path',
        ),
        migrations.RemoveField(
            model_name='media',
            name='upload_by',
        ),
        migrations.RemoveField(
            model_name='media',
            name='version',
        ),
    ]
